version: "3.5"
services:

  # Orion is the context broker
  orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: orion
    depends_on:
      - mongo
    networks:
      - reflex
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongo -corsOrigin __ALL -logLevel DEBUG -noCache
  
  # Cygnus is configured to write context data
  cygnus:
    image: fiware/cygnus-ngsi:latest
    hostname: cygnus
    container_name: cygnus
    depends_on:
      - mongo
    networks:
      - reflex
    expose:
      - "5080"
    ports:
      - "5080:5080" 
      - "5050:5050"
      - "5051:5051"
    environment:
      - "CYGNUS_MULTIAGENT=true"
      - "CYGNUS_MONGO_HOSTS=mongo:27017"
      - "CYGNUS_LOG_LEVEL=DEBUG"
      #- "CYGNUS_SERVICE_PORT=5050"
      #- "CYGNUS_API_PORT=5080"      
      
  # Databases - Orion uses Mongo-DB, Cygnus is persisting
  mongo:
    image: mongo:3.6
    hostname: mongo
    container_name: mongo
    networks:
      - reflex
    expose:
      - "27017"
    command: --bind_ip_all --smallfiles
    volumes:
      - mongo:/data
  
networks:
  reflex:
    driver: bridge
    
volumes:
  mongo: ~