version: "3.5"
services:

  # Orion is the context broker
  orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: orion
    depends_on:
      - mongo
      - mysql-db
    networks:
      - reflex
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongo -corsOrigin __ALL -logLevel DEBUG -noCache
    
    # Cygnus is configured to write context data
  cygnus:
    image: fiware/cygnus-ngsi:latest
    hostname: cygnus
    container_name: cygnus
    depends_on:
      - mongo
      - mysql-db
    networks:
      - reflex
    expose:
      - "5080"
    ports:
      - "5080:5080" 
      - "5050:5050"
      - "5051:5051"
    environment:
      - "CYGNUS_MULTIAGENT=true"
      - "CYGNUS_MONGO_HOSTS=mongo:27017"
      - "CYGNUS_LOG_LEVEL=DEBUG"
      #- "CYGNUS_SERVICE_PORT=5050"
      #- "CYGNUS_API_PORT=5080"
      
      #inclui as linhas do mysql 21-05-2022
      - "CYGNUS_MYSQL_HOST=mysql-db"
      - "CYGNUS_MYSQL_PORT=3306"
      - "CYGNUS_MYSQL_USER=root"
      - "CYGNUS_MYSQL_PASS=123"
      - "CYGNUS_MYSQL_SERVICE_PORT=5050"
     
  iotagentul:
    image: fiware/iotagent-ul:latest
    hostname: iotagentul
    container_name: iotagentul
    depends_on:
      - mongodb
      - mysql-db
    networks:
      - reflex
    expose:
      - "4061"
      - "7896"
    ports:
      - "4061:4061"
      - "7896:7896"
    environment:
      - "IOTA_CB_HOST=orion"
      - "IOTA_CB_PORT=1026"
      - "IOTA_NORTH_PORT=4061"
      - "IOTA_REGISTRY_TYPE=mongodb"
      - "IOTA_MONGO_HOST=mongodb"
      - "IOTA_MONGO_PORT=27017"
      - "IOTA_MONGO_DB=iotagentul"
      - "IOTA_HTTP_PORT=7896"
      - "IOTA_PROVIDER_URL=http://iotagentul:4061"  
  
  agentjson:
    image: fiware/iotagent-json:latest
    hostname: agentjson
    container_name: agentjson
    depends_on:
      - mongo
      - mysql-db
    networks:
      - reflex
    expose:
      - "4041"
      - "7896"
    ports:
      - "4041:4041"
      - "7896:7896"
    environment:
      - "IOTA_CB_HOST=orion"
      - "IOTA_CB_PORT=1026"
      - "IOTA_NORTH_PORT=4041"
      - "IOTA_REGISTRY_TYPE=mongo"
      - "IOTA_MONGO_HOST=mongo"
      - "IOTA_MONGO_PORT=27017"
      - "IOTA_MONGO_DB=agentjson"
      - "IOTA_HTTP_PORT=7896"
      - "IOTA_PROVIDER_URL=http://agentjson:4041"
  
  
  # STH-Comet is persisting Short Term History to Mongo-DB
  sth:
    image: fiware/sth-comet:latest
    hostname: sth
    container_name: sth
    volumes:
      - /home/ubuntu/sth/config.js:/opt/sth/config.js
    depends_on:
      - mongo
    networks:
      - reflex
    expose:
      - "8666"
    ports:
      - "8666:8666"
    environment:
      - STH_HOST=sth
      - STH_PORT=8666
      - DB_URI=mongo:27017
      - LOGOPS_LEVEL=DEBUG
      
  # Engine Rule CEP
  perseo-core:
    image: fiware/perseo-core
    container_name: core
    hostname: perseo-core
    environment:
      - PERSEO_FE_URL=http://perseo-fe:9090
      - MAX_AGE=6000
    networks:
      - reflex
    depends_on:
      - mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
 
  # API Front end CEP 
  perseo-fe:
    image: fiware/perseo
    hostname: perseo-fe
    container_name: fe
    networks:
      reflex:            
    expose:
      - "9090"
    depends_on:
      - perseo-core
    environment:
      - PERSEO_MONGO_ENDPOINT=mongo:27017
      - PERSEO_CORE_URL=http://perseo-core:8080
      - PERSEO_LOG_LEVEL=debug
      - PERSEO_ORION_URL=http://orion:1026/
      - PERSEO_SMTP_HOST=smtp.gmail.com
      - PERSEO_SMTP_SECURE=true
      - PERSEO_SMTP_PORT=465
      - PERSEO_SMTP_AUTH_USER=reflexwater2020@gmail.com
      - PERSEO_SMTP_AUTH_PASS=reflexreflex
      - PERSEO_DEFAULT_SERVICE=reflexiot
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
                
# grafana used for graphing mysql data
  grafana:
    image: grafana/grafana-oss:latest
    hostname: grafana
    container_name: grafana
    #restart: always
    ports:
        - 3000:3000
    #environment:
    #  GF_INSTALL_PLUGINS:
    networks:
        - reflex
    volumes:
        - grafana:/data
    depends_on:
        - mongo 
        - mysql-db
        - cygnus
        - orion
        - sth
        
# Databases - Orion uses Mysql, Cygnus is persisting
  mysql-db:
    #restart: always
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    expose:
        - "3306"
    ports:
        - "3306:3306"
    networks:
        - reflex
    environment:
        - "MYSQL_ROOT_PASSWORD=123"
        - "MYSQL_ROOT_HOST=%"        
    volumes:
      - mysql:/data
      
  # Databases - Orion uses Mongo-DB, Cygnus is persisting
  mongo:
    image: mongo:3.6
    hostname: mongo
    container_name: mongo
    networks:
      - reflex
    expose:
      - "27017"
    command: --bind_ip_all --smallfiles
    volumes:
      - mongo:/data
  
networks:
  reflex:
    driver: bridge
    
volumes:
  mongo: ~
  mysql: ~
  grafana: ~